const streamsTypes = {
  FETCH_STREAMS_START: "FETCH_STREAMS_START",
  SET_STREAMS: "SET_STREAMS",
  FETCH_SLIDESHOW_STREAMS_START: "FETCH_SLIDESHOW_STREAMS_START",
  SET_SLIDESHOW_STREAMS: "SET_SLIDESHOW_STREAMS",
  FETCH_STREAM_DATA_START: "FETCH_STREAM_DATA_START",
  SET_STREAM_DATA: "SET_STREAM_DATA",
  FETCH_SPONSORS_START: "FETCH_SPONSORS_START",
  SET_SPONSORS: "SET_SPONSORS",
};

export default streamsTypes;
