const userTypes = {
  CHECK_USER_SESSION: "CHECK_USER_SESSION",
  RESET_USER_STATE: "RESET_USER_STATE",
  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_ERRORS: "SIGN_IN_ERRORS",
  SIGN_OUT_USER_START: "SIGN_OUT_USER_START",
  SIGN_OUT_USER_SUCCESS: "SIGN_OUT_USER_SUCCESS",
  SIGN_UP_USER_START: "SIGN_UP_USER_START",
  SIGN_UP_ERRORS: "SIGN_UP_ERRORS",
};

export default userTypes;
